import { Router } from 'express'; import { z } from 'zod'; import { prisma } from '../lib/prisma.js'; import { auth, roles } from '../middleware/auth.js';
const r=Router();
r.get('/me',auth(),async(req,res)=>res.json(await prisma.user.findUnique({where:{id:req.user.sub},include:{wallet:true,addresses:true}})));
r.patch('/me',auth(),async(req,res)=>{const s=z.object({name:z.string().min(1).max(100).optional(),email:z.string().email().optional()}).parse(req.body);res.json(await prisma.user.update({where:{id:req.user.sub},data:s}));});
r.get('/doctors',async(req,res)=>res.json(await prisma.doctor.findMany({where:{active:true},include:{user:true,availabilities:true}})));
r.get('/services',async(req,res)=>res.json(await prisma.service.findMany({where:{active:true}})));
r.get('/labs',async(req,res)=>res.json(await prisma.labTest.findMany({where:{active:true}})));
r.get('/medicines',async(req,res)=>res.json(await prisma.medicine.findMany({where:{active:true,stock:{gt:0}}})));
r.get('/addresses',auth(),async(req,res)=>res.json(await prisma.address.findMany({where:{userId:req.user.sub}})));
r.post('/addresses',auth(),async(req,res)=>{const s=z.object({label:z.string(),line1:z.string(),city:z.string(),state:z.string(),pincode:z.string().min(4)}).parse(req.body);res.status(201).json(await prisma.address.create({data:{...s,userId:req.user.sub}}));});
r.get('/bookings',auth(),async(req,res)=>res.json(await prisma.booking.findMany({where:{userId:req.user.sub},include:{doctor:{include:{user:true}},service:true,consultation:true,payment:true},orderBy:{scheduledAt:'desc'}})));
r.post('/bookings',auth(),async(req,res)=>{const s=z.object({doctorId:z.string().optional(),serviceId:z.string().optional(),scheduledAt:z.coerce.date(),consultationType:z.enum(['VIDEO','VOICE']).optional(),amount:z.number().int().nonnegative().default(0)}).refine(v=>v.doctorId||v.serviceId,{message:'doctorId or serviceId required'}).parse(req.body);const b=await prisma.booking.create({data:{...s,userId:req.user.sub,status:'PENDING'}});if(s.consultationType)await prisma.consultation.create({data:{bookingId:b.id,type:s.consultationType,startsAt:s.scheduledAt}});res.status(201).json(b);});
r.get('/records',auth(),async(req,res)=>res.json(await prisma.healthRecord.findMany({where:{userId:req.user.sub},orderBy:{createdAt:'desc'}})));
r.get('/prescriptions',auth(),async(req,res)=>res.json(await prisma.prescription.findMany({where:{userId:req.user.sub},orderBy:{createdAt:'desc'}})));
r.get('/family',auth(),async(req,res)=>res.json(await prisma.familyMember.findMany({where:{userId:req.user.sub}})));
r.post('/family',auth(),async(req,res)=>{const s=z.object({name:z.string(),relation:z.string(),phone:z.string().optional()}).parse(req.body);res.status(201).json(await prisma.familyMember.create({data:{...s,userId:req.user.sub}}));});
r.get('/wallet',auth(),async(req,res)=>res.json(await prisma.wallet.upsert({where:{userId:req.user.sub},create:{userId:req.user.sub},update:{},include:{transactions:{orderBy:{createdAt:'desc'},take:50}}})));
r.get('/notifications',auth(),async(req,res)=>res.json(await prisma.notification.findMany({where:{userId:req.user.sub},orderBy:{createdAt:'desc'},take:100})));
r.post('/admin/services',auth(),roles('ADMIN'),async(req,res)=>{const s=z.object({name:z.string(),category:z.string(),description:z.string().optional(),price:z.number().int().nonnegative()}).parse(req.body);res.status(201).json(await prisma.service.create({data:s}));});
r.post('/admin/doctors',auth(),roles('ADMIN'),async(req,res)=>{const s=z.object({phone:z.string(),name:z.string(),specialty:z.string(),qualification:z.string().optional(),experienceYears:z.number().int().nonnegative().default(0),fee:z.number().int().nonnegative().default(0)}).parse(req.body);const u=await prisma.user.create({data:{phone:s.phone,name:s.name,role:'DOCTOR'}});const d=await prisma.doctor.create({data:{userId:u.id,specialty:s.specialty,qualification:s.qualification,experienceYears:s.experienceYears,fee:s.fee}});res.status(201).json(d);});
export default r;
